# Generated by Django 4.1.2 on 2022-10-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_studentform_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFormq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Enter first name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Enter last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Enter Email')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentForm',
        ),
    ]
