# Generated by Django 4.1.2 on 2022-10-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_studentformq_delete_studentform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentformq',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentformq',
            name='lastname',
        ),
    ]
