# Generated by Django 4.1.1 on 2022-10-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_studentformq_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='studentformq',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='Enter unit name'),
        ),
    ]
