# Generated by Django 4.1.2 on 2022-10-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_rename_desc_quiz_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentformq',
            name='subject',
            field=models.CharField(choices=[('mccp', 'MCCP'), ('ai', 'AI'), ('dm', 'DM'), ('os', 'OS'), ('wt', 'WT')], max_length=10, null=True),
        ),
    ]
