# Generated by Django 4.1.2 on 2022-10-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_studentformq_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentformq',
            name='subject',
            field=models.CharField(choices=[('MCCP', 'MCCP'), ('AI', 'AI'), ('DM', 'DM'), ('OS', 'OS'), ('WT', 'WT')], max_length=10, null=True),
        ),
    ]
